### ISSUE TITLE
compare_version() uses new without delete

### ISSUE THREAD

**Issue by BryanStuurman** [xArm-Developer/xArm-CPLUS-SDK#11]
Inside set_tcp_load() makes a call to compare_version() with a new:
`if (compare_version(version_number, new int[3]{ 0, 2, 0 })) {`
https://github.com/xArm-Developer/xArm-CPLUS-SDK/blob/master/src/xarm/wrapper/xarm_params.cc#L59

In my understanding, the pointer returned by new is lost when the function returns, however the memory remains allocated until delete can be called on that pointer (new is not affected by scope) - this would be a memory leak.

**Comment by vimior** [comment]
@BryanStuurman 
thanks for reminding.

**Comment by BryanStuurman** [comment]
Looks good, thanks!
a closing note: code that subrepos this SDK should probably be updated to point to this most recent commit as well.
