### ISSUE TITLE
get_inverse_kinematics returns current robot angles

### ISSUE THREAD

**Issue by traitorus** [xArm-Developer/xArm-CPLUS-SDK#2]
get_inverse_kinematics(f32* pose, f32* angles)
returns the current robot angles (with slight offset) instead of the angles needed to reach the input Cartesian pose.

I'm trying to perform a NON linear motion (point to point) with Cartesian coordinates, hence I would like to use set_servo_angle(angles, speed, acc, mvtime, wait, timeout) with the angles calculated from inverse kinematics.

Or is there another way to achieve this ?

**Comment by rjs5327** [comment]
I am having a similar issue where the get inverse kinetics is not working properly

**Comment by vimior** [comment]
The results obtained by this interface will be affected by the current position of the robotic arm, which is not recommended for the time being

**Comment by rjs5327** [comment]
Is there a expected firmware update to address this in the pipeline?

**Comment by MinnaZhong** [comment]
We have optimized get_inverse_kinematics, please update to the latest firmware and xArmStudio version to V1.8.5 to test.

Issued closed.
