### ISSUE TITLE
No smooth motion between Joint, Linear & Circle motions

### ISSUE THREAD

**Issue by traitorus** [xArm-Developer/xArm-CPLUS-SDK#3]
There is no smooth motion if the following motion commands are called consecutively, meaning the xArm6 robot has to stop in between both motions:
Basically every command except set_position() with a radius superior to 0 (and wait=false).

Is there a way to achieve different kinds of motion smoothly ?

**Comment by vimior** [comment]
Currently, there are ways to achieve smooth motion
1. move lineb: Use set_position interface, but to set the parameter radius greater than or equal to 0 and wait = false, you can refer to routine 1004-move_arc_line.cc
2. Using servoj mode, you can refer to routines 7001-servo_j.cc and 7002-servo_cartesian.cc
