### ISSUE TITLE
example/8002-impedance.cc not working

### ISSUE THREAD

**Issue by AntoBongio** [xArm-Developer/xArm-CPLUS-SDK#8]
Hi,

I am testing the new functionalities added with the 1.8.0 version, but I can not make work the example of impedance control. 
After I enable the sensore, I receive the error code: 50 (Force sensor read error). 
There is something missing in this example? 

Thanks for your attention. I am looking forward to your reply.

**Comment by MinnaZhong** [comment]
Case 8001 to 8010 can only be used with our 6 Axis Force Torque Sensor.
The user manual of 6 Axis Force Torque Sensor can be downloaded in : https://www.ufactory.cc/pages/download-xarm

Issue closed.
